CREATE TABLE core.dim_payment(
	payment_pk INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1),
	payment	VARCHAR,
	loyalty_card	VARCHAR,
	PRIMARY KEY(payment_pk)
);

SELECT * FROM core.dim_payment;



--SELECT DISTINCT COALESCE(payment,'cash' ) AS payment, loyalty_card FROM staging.sales;

