-- Table: staging.dim_product

-- DROP TABLE IF EXISTS staging.dim_product;

CREATE TABLE staging.dim_product
(
    product_pk integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1),
    product_id VARCHAR,
    product_name VARCHAR,
    category  VARCHAR,
    subcategory VARCHAR,
    PRIMARY KEY (product_pk)
);

SELECT * FROM staging.dim_product;